In [1]:
import pandas as pd
data = pd.read_csv('training_data.csv')
x = list(data['text'])

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vt = CountVectorizer()
vt.fit(x)
xbof = vt.transform(x)

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit(x)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [4]:
import numpy as np
np.set_printoptions(precision=2)
r = tfidf.transform(x).toarray()
print(r)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
data2 = pd.read_csv('test_data.csv')
x2 = list(data2['text'])

In [6]:
xbof = vt.transform(x2)
np.set_printoptions(precision=2)
r2 = tfidf.transform(x2).toarray()
print(r2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
s = data['stars']

In [8]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(r,s)
A = list(pd.DataFrame(lr.predict(r2))[0])

In [9]:
idd = data2['review_id']
result = pd.DataFrame(A,index = idd)
z = result[0]
z.to_csv(r"C:\Python35-32\workspace\out3.csv")